# Generated by Django 3.1.1 on 2020-09-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_length', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='queue_length',
            field=models.IntegerField(default=0),
        ),
    ]
