# Generated by Django 3.1.1 on 2020-09-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_length', '0006_auto_20200926_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logdata_put',
            name='date_time_put',
        ),
        migrations.AddField(
            model_name='logdata_put',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='queue_length'),
        ),
    ]
