# Generated by Django 3.1.1 on 2020-09-26 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue_length', '0007_auto_20200926_1004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Queue',
        ),
    ]
