# Generated by Django 3.1.1 on 2020-09-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_length', '0008_delete_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdata_put',
            name='queue_length',
            field=models.IntegerField(default=0),
        ),
    ]
